import 'package:algarve_house_hunters_system/customer_dashboard_screen/model/property_model.dart';

class AgentListingScreenController {
  static List<String> propertyImagePaths = [
    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'https://plus.unsplash.com/premium_photo-1686090449192-4ab1d00cb735?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'https://plus.unsplash.com/premium_photo-1687960117069-567a456fe5f3?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'https://images.unsplash.com/photo-1483097365279-e8acd3bf9f18?q=80&w=2011&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'https://images.unsplash.com/photo-1516156008625-3a9d6067fab5?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'https://images.unsplash.com/photo-1498373419901-52eba931dc4f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'https://images.unsplash.com/photo-1472224371017-08207f84aaae?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  ];
  static List<PropertyModel> getSampleRecentlyAddedPropertyList() => [
        PropertyModel(
          ourRef: 'https://infocasa.pt/realestates/7155424',
          listingRef: '322/M/02127',
          contactEmail: 'vrsa@era.pt',
          price: 159900,
          propertyM2: 112,
          clientLink: 'https://url.infocasa.pt/cvwd3a30',
          location: 'Ribeira da Gafa',
          bedsNumber: 2,
          bathsNumber: 3,
          plotNumber: 515,
          distanceFromCoast: 12,
          googleMapLink: 'https://maps.app.goo.gl/jxNqTsRPYpVd9uTu9',
          propertyDescription: "This the sample property description",
          propertyImages: propertyImagePaths,
          propertyName: 'Recently added property 1',
          propertyId: 'afshghgshagsh2',
        ),
        PropertyModel(
          ourRef: 'https://infocasa.pt/realestates/7155424',
          listingRef: '322/M/02128',
          contactEmail: 'vrsa@era.pt',
          price: 159900,
          propertyM2: 112,
          clientLink: 'https://url.infocasa.pt/cvwd3a30',
          location: 'Ribeira da Gafa',
          bedsNumber: 2,
          bathsNumber: 3,
          plotNumber: 515,
          distanceFromCoast: 12,
          googleMapLink: 'https://maps.app.goo.gl/jxNqTsRPYpVd9uTu9',
          propertyDescription: "This the sample property description",
          propertyImages: propertyImagePaths,
          propertyName: 'Recently added property 8',
          propertyId: 'afshghgshagsh',
        ),
        PropertyModel(
          ourRef: 'https://infocasa.pt/realestates/7155424',
          listingRef: '322/M/02129',
          contactEmail: 'vrsa@era.pt',
          price: 159900,
          propertyM2: 112,
          clientLink: 'https://url.infocasa.pt/cvwd3a30',
          location: 'Ribeira da Gafa',
          bedsNumber: 2,
          bathsNumber: 3,
          plotNumber: 515,
          distanceFromCoast: 12,
          googleMapLink: 'https://maps.app.goo.gl/jxNqTsRPYpVd9uTu9',
          propertyDescription: "This the sample property description",
          propertyImages: propertyImagePaths,
          propertyName: 'Recently added property 3',
          propertyId: 'afshghgshagsh1',
        )
      ];

  static List<PropertyModel> getSampleMyPropertyList() => [
        PropertyModel(
          ourRef: 'https://infocasa.pt/realestates/7155424',
          listingRef: '322/M/02127',
          contactEmail: 'vrsa@era.pt',
          price: 159900,
          propertyM2: 112,
          clientLink: 'https://url.infocasa.pt/cvwd3a30',
          location: 'Ribeira da Gafa',
          bedsNumber: 2,
          bathsNumber: 3,
          plotNumber: 515,
          distanceFromCoast: 12,
          googleMapLink: 'https://maps.app.goo.gl/jxNqTsRPYpVd9uTu9',
          propertyDescription: "This the sample property description",
          propertyImages: propertyImagePaths,
          propertyName: 'Recently added property 1',
          propertyId: 'afshghgshagsh2',
        ),
        PropertyModel(
          ourRef: 'https://infocasa.pt/realestates/7155424',
          listingRef: '322/M/02128',
          contactEmail: 'vrsa@era.pt',
          price: 159900,
          propertyM2: 112,
          clientLink: 'https://url.infocasa.pt/cvwd3a30',
          location: 'Ribeira da Gafa',
          bedsNumber: 2,
          bathsNumber: 3,
          plotNumber: 515,
          distanceFromCoast: 12,
          googleMapLink: 'https://maps.app.goo.gl/jxNqTsRPYpVd9uTu9',
          propertyDescription: "This the sample property description",
          propertyImages: propertyImagePaths,
          propertyName: 'Recently added property 8',
          propertyId: 'afshghgshagsh',
        ),
        PropertyModel(
          ourRef: 'https://infocasa.pt/realestates/7155424',
          listingRef: '322/M/02129',
          contactEmail: 'vrsa@era.pt',
          price: 159900,
          propertyM2: 112,
          clientLink: 'https://url.infocasa.pt/cvwd3a30',
          location: 'Ribeira da Gafa',
          bedsNumber: 2,
          bathsNumber: 3,
          plotNumber: 515,
          distanceFromCoast: 12,
          googleMapLink: 'https://maps.app.goo.gl/jxNqTsRPYpVd9uTu9',
          propertyDescription: "This the sample property description",
          propertyImages: propertyImagePaths,
          propertyName: 'Recently added property 3',
          propertyId: 'afshghgshagsh1',
        )
      ];
  static List<PropertyModel> getSampleMostLikedPropertyList() => [
        PropertyModel(
          ourRef: 'https://infocasa.pt/realestates/7155424',
          listingRef: '322/M/02127',
          contactEmail: 'vrsa@era.pt',
          price: 159900,
          propertyM2: 112,
          clientLink: 'https://url.infocasa.pt/cvwd3a30',
          location: 'Ribeira da Gafa',
          bedsNumber: 2,
          bathsNumber: 3,
          plotNumber: 515,
          distanceFromCoast: 12,
          googleMapLink: 'https://maps.app.goo.gl/jxNqTsRPYpVd9uTu9',
          propertyDescription: "This the sample property description",
          propertyImages: propertyImagePaths,
          propertyName: 'Recently added property 1',
          propertyId: 'afshghgshagsh2',
        ),
        PropertyModel(
          ourRef: 'https://infocasa.pt/realestates/7155424',
          listingRef: '322/M/02128',
          contactEmail: 'vrsa@era.pt',
          price: 159900,
          propertyM2: 112,
          clientLink: 'https://url.infocasa.pt/cvwd3a30',
          location: 'Ribeira da Gafa',
          bedsNumber: 2,
          bathsNumber: 3,
          plotNumber: 515,
          distanceFromCoast: 12,
          googleMapLink: 'https://maps.app.goo.gl/jxNqTsRPYpVd9uTu9',
          propertyDescription: "This the sample property description",
          propertyImages: propertyImagePaths,
          propertyName: 'Recently added property 8',
          propertyId: 'afshghgshagsh',
        ),
        PropertyModel(
          ourRef: 'https://infocasa.pt/realestates/7155424',
          listingRef: '322/M/02129',
          contactEmail: 'vrsa@era.pt',
          price: 159900,
          propertyM2: 112,
          clientLink: 'https://url.infocasa.pt/cvwd3a30',
          location: 'Ribeira da Gafa',
          bedsNumber: 2,
          bathsNumber: 3,
          plotNumber: 515,
          distanceFromCoast: 12,
          googleMapLink: 'https://maps.app.goo.gl/jxNqTsRPYpVd9uTu9',
          propertyDescription: "This the sample property description",
          propertyImages: propertyImagePaths,
          propertyName: 'Recently added property 3',
          propertyId: 'afshghgshagsh1',
        )
      ];
}
